name: Build and Push Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'FitnessTracker/**/*.csproj' # Trigger on changes to any .csproj files in the FitnessTracker directory
      - 'FitnessTracker/**/*.cs'     # Trigger on changes to any .cs files in the FitnessTracker directory
      - Dockerfile                   # Trigger on changes to the Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fitness:latest .
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/fitness:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fitness:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fitness:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fitness:${{ github.sha }}
